<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>JobPlatform.DbAdmin</RootNamespace>
    <AzureCosmosDisableNewtonsoftJsonCheck>true</AzureCosmosDisableNewtonsoftJsonCheck>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\JobPlatform.Data\JobPlatform.Data.csproj" />
  </ItemGroup>

</Project>
