// <auto-generated />
using System;
using JobPlatform.Data.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobPlatform.Data.Sql.Migrations
{
    [DbContext(typeof(JobsDbContext))]
    [Migration("20260821111724_PerSearchTermAttribution")]
    partial class PerSearchTermAttribution
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.JobPostingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Company")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CompanyIndustry")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanyNumEmployees")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateOnly?>("DatePosted")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DescriptionLength")
                        .HasColumnType("int");

                    b.Property<string>("ExperienceRange")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("FakeFreshness")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FirstSeenUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FreshnessClass")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsRemote")
                        .HasColumnType("bit");

                    b.Property<string>("JobFunction")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("JobLevel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("JobType")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("JobUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("JobUrlDirect")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LocationCity")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LocationCountry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LocationRaw")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("LocationRegion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("MaxAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("MinAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("PostingAgeDays")
                        .HasColumnType("int");

                    b.Property<int?>("RepostCount")
                        .HasColumnType("int");

                    b.Property<string>("SalaryInterval")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SalarySource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SeenCount")
                        .HasColumnType("int");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Company");

                    b.HasIndex("ContentHash");

                    b.HasIndex("FreshnessClass");

                    b.HasIndex("LastSeenUtc");

                    b.HasIndex("SourceKey")
                        .IsUnique();

                    b.ToTable("JobPostings", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.JobPostingSearchTerm", b =>
                {
                    b.Property<long>("PostingId")
                        .HasColumnType("bigint");

                    b.Property<string>("SearchTerm")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FirstSeenRunId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("FirstSeenUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LastSeenRunId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SeenCount")
                        .HasColumnType("int");

                    b.HasKey("PostingId", "SearchTerm");

                    b.HasIndex("FirstSeenRunId");

                    b.HasIndex("LastSeenRunId");

                    b.HasIndex("SearchTerm", "FirstSeenUtc");

                    b.HasIndex("SearchTerm", "LastSeenUtc");

                    b.ToTable("JobPostingSearchTerms", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ScrapeRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobETag")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long>("BlobSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("DurationMs")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("IngestedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("InvalidCount")
                        .HasColumnType("int");

                    b.Property<int>("NewCount")
                        .HasColumnType("int");

                    b.Property<int>("ParsedCount")
                        .HasColumnType("int");

                    b.Property<int>("RowCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ScrapeDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("ScrapedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SearchTerm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UnchangedCount")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlobPath")
                        .IsUnique();

                    b.HasIndex("SearchTerm", "ScrapeDate");

                    b.ToTable("ScrapeRuns", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.JobPostingSearchTerm", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.ScrapeRun", "FirstSeenRun")
                        .WithMany()
                        .HasForeignKey("FirstSeenRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobPlatform.Data.Sql.Entities.ScrapeRun", "LastSeenRun")
                        .WithMany()
                        .HasForeignKey("LastSeenRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobPlatform.Data.Sql.Entities.JobPostingEntity", "Posting")
                        .WithMany("SearchTerms")
                        .HasForeignKey("PostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirstSeenRun");

                    b.Navigation("LastSeenRun");

                    b.Navigation("Posting");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.JobPostingEntity", b =>
                {
                    b.Navigation("SearchTerms");
                });
#pragma warning restore 612, 618
        }
    }
}
