// <auto-generated />
using System;
using JobPlatform.Data.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobPlatform.Data.Sql.Migrations
{
    [DbContext(typeof(JobsDbContext))]
    partial class JobsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ApplicationDocumentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CoverLetterMarkdown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CurriculumVitaeMarkdown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmphasisedJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("PostingId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.Property<int>("WriterVersion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostingId");

                    b.HasIndex("ProfileId", "CreatedAtUtc");

                    b.HasIndex("ProfileId", "PostingId", "Revision")
                        .IsUnique();

                    b.ToTable("ApplicationDocuments", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.CandidateProfileEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTimeOffset?>("ExtractedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExtractionInputHash")
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("ExtractionModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExtractionPayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExtractorVersion")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Headline")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("LocationCity")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LocationCountry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaxDaysInOffice")
                        .HasColumnType("int");

                    b.Property<decimal?>("MinimumSalary")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PreferredArrangement")
                        .HasColumnType("int");

                    b.Property<string>("SalaryCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Seniority")
                        .HasColumnType("int");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("WillingToRelocate")
                        .HasColumnType("bit");

                    b.Property<int?>("YearsExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId")
                        .IsUnique();

                    b.ToTable("CandidateProfiles", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.CompanyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("EmployeesBand")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("EmployeesMax")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeesMin")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("FirstSeenUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Industry")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Revenue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ReviewsCount")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyKey")
                        .IsUnique();

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ConceptClosureEntity", b =>
                {
                    b.Property<int>("AncestorId")
                        .HasColumnType("int");

                    b.Property<int>("DescendantId")
                        .HasColumnType("int");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.HasKey("AncestorId", "DescendantId");

                    b.HasIndex("DescendantId", "AncestorId");

                    b.ToTable("ConceptClosure", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ConceptEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConceptKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("PrefLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TaxonomyVersion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConceptKey")
                        .IsUnique();

                    b.HasIndex("Kind");

                    b.ToTable("Concepts", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ConceptLabelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConceptId")
                        .HasColumnType("int");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedLabel");

                    b.HasIndex("ConceptId", "NormalizedLabel")
                        .IsUnique();

                    b.ToTable("ConceptLabels", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ConceptRelationEntity", b =>
                {
                    b.Property<int>("FromConceptId")
                        .HasColumnType("int");

                    b.Property<int>("ToConceptId")
                        .HasColumnType("int");

                    b.Property<int>("RelationType")
                        .HasColumnType("int");

                    b.HasKey("FromConceptId", "ToConceptId", "RelationType");

                    b.HasIndex("ToConceptId", "RelationType");

                    b.ToTable("ConceptRelations", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ExtractionBatchEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Failed")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProviderBatchId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Requested")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Succeeded")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProviderBatchId")
                        .IsUnique();

                    b.HasIndex("State", "SubmittedAtUtc");

                    b.ToTable("ExtractionBatches", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ExtractionBatchItemEntity", b =>
                {
                    b.Property<long>("BatchId")
                        .HasColumnType("bigint");

                    b.Property<long>("PostingId")
                        .HasColumnType("bigint");

                    b.Property<string>("InputHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.HasKey("BatchId", "PostingId");

                    b.HasIndex("PostingId");

                    b.ToTable("ExtractionBatchItems", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.JobMatchEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("AssessedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AssessmentGapsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssessmentModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AssessmentPayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AssessmentScore")
                        .HasColumnType("int");

                    b.Property<int?>("AssessmentVersion")
                        .HasColumnType("int");

                    b.Property<string>("ComponentsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmphasiseJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GapsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatchedJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PostingId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<double>("RankScore")
                        .HasColumnType("float");

                    b.Property<int>("RankerVersion")
                        .HasColumnType("int");

                    b.Property<string>("Rationale")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("RequiredGapCount")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ScoredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ScorerVersion")
                        .HasColumnType("int");

                    b.Property<double?>("Similarity")
                        .HasColumnType("float");

                    b.Property<string>("StrengthsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Verdict")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostingId");

                    b.HasIndex("ProfileId", "AssessedAtUtc");

                    b.HasIndex("ProfileId", "PostingId")
                        .IsUnique();

                    b.HasIndex("ProfileId", "RankScore");

                    b.HasIndex("ProfileId", "Score");

                    b.ToTable("JobMatches", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.JobPostingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AnnualSalaryCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("AnnualSalaryMax")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("AnnualSalaryMin")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("ApplicantCount")
                        .HasColumnType("int");

                    b.Property<string>("Applicants")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Company")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyIndustry")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanyNumEmployees")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateOnly?>("DatePosted")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DescriptionLength")
                        .HasColumnType("int");

                    b.Property<int>("EnrichmentVersion")
                        .HasColumnType("int");

                    b.Property<string>("ExperienceRange")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("FakeFreshness")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FirstSeenUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FreshnessClass")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("HasContactEmail")
                        .HasColumnType("bit");

                    b.Property<int?>("HybridDaysInOffice")
                        .HasColumnType("int");

                    b.Property<string>("Ir35")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("IsRemote")
                        .HasColumnType("bit");

                    b.Property<string>("JobFunction")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("JobLevel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("JobType")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("JobUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("JobUrlDirect")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ListingType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LocationCity")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LocationCountry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LocationRaw")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("LocationRegion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("MaxAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("MinAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool?>("OffsiteApply")
                        .HasColumnType("bit");

                    b.Property<int?>("PostingAgeDays")
                        .HasColumnType("int");

                    b.Property<int?>("RepostCount")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresDegree")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresSecurityClearance")
                        .HasColumnType("bit");

                    b.Property<int>("RoleFamily")
                        .HasColumnType("int");

                    b.Property<bool>("SalaryFromText")
                        .HasColumnType("bit");

                    b.Property<string>("SalaryInterval")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SalarySource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SalaryStatedInterval")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SeenCount")
                        .HasColumnType("int");

                    b.Property<int>("Seniority")
                        .HasColumnType("int");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SourceBoard")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("VacancyCount")
                        .HasColumnType("int");

                    b.Property<bool?>("VisaSponsorship")
                        .HasColumnType("bit");

                    b.Property<int>("WorkArrangement")
                        .HasColumnType("int");

                    b.Property<string>("WorkFromHomeType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("YearsExperienceMax")
                        .HasColumnType("int");

                    b.Property<int?>("YearsExperienceMin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Company");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContentHash");

                    b.HasIndex("EnrichmentVersion");

                    b.HasIndex("FreshnessClass");

                    b.HasIndex("LastSeenUtc");

                    b.HasIndex("RoleFamily");

                    b.HasIndex("Seniority");

                    b.HasIndex("SourceBoard");

                    b.HasIndex("SourceKey")
                        .IsUnique();

                    b.HasIndex("WorkArrangement");

                    b.HasIndex("Company", "LocationCity");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Company", "LocationCity"), new[] { "Title", "JobUrlDirect", "Site" });

                    b.ToTable("JobPostings", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.JobPostingJobTypeEntity", b =>
                {
                    b.Property<long>("PostingId")
                        .HasColumnType("bigint");

                    b.Property<string>("JobType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PostingId", "JobType");

                    b.HasIndex("JobType");

                    b.ToTable("JobPostingJobTypes", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.JobPostingSearchTerm", b =>
                {
                    b.Property<long>("PostingId")
                        .HasColumnType("bigint");

                    b.Property<string>("SearchTerm")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FirstSeenRunId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("FirstSeenUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LastSeenRunId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SeenCount")
                        .HasColumnType("int");

                    b.HasKey("PostingId", "SearchTerm");

                    b.HasIndex("FirstSeenRunId");

                    b.HasIndex("LastSeenRunId");

                    b.HasIndex("SearchTerm", "FirstSeenUtc");

                    b.HasIndex("SearchTerm", "LastSeenUtc");

                    b.ToTable("JobPostingSearchTerms", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.PostingConceptEntity", b =>
                {
                    b.Property<long>("PostingId")
                        .HasColumnType("bigint");

                    b.Property<int>("ConceptId")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<double?>("Confidence")
                        .HasColumnType("float");

                    b.Property<string>("EvidenceText")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Polarity")
                        .HasColumnType("int");

                    b.Property<int>("ResolverVersion")
                        .HasColumnType("int");

                    b.Property<int?>("YearsMax")
                        .HasColumnType("int");

                    b.Property<int?>("YearsMin")
                        .HasColumnType("int");

                    b.HasKey("PostingId", "ConceptId", "Source");

                    b.HasIndex("ResolverVersion");

                    b.HasIndex("ConceptId", "PostingId");

                    b.ToTable("PostingConcepts", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.PostingEmbeddingEntity", b =>
                {
                    b.Property<long>("PostingId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<int>("DescriptionLength")
                        .HasColumnType("int");

                    b.Property<int>("Dimensions")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("EmbeddedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EmbeddingVersion")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Vector")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("PostingId");

                    b.ToTable("PostingEmbeddings", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.PostingExtractionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ExtractedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ExtractorVersion")
                        .HasColumnType("int");

                    b.Property<string>("InputHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PostingId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PostingId", "ExtractorVersion", "InputHash")
                        .IsUnique();

                    b.ToTable("PostingExtractions", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.PostingMentionEntity", b =>
                {
                    b.Property<long>("PostingId")
                        .HasColumnType("bigint");

                    b.Property<string>("SurfaceForm")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Occurrences")
                        .HasColumnType("int");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<int>("ResolverVersion")
                        .HasColumnType("int");

                    b.HasKey("PostingId", "SurfaceForm");

                    b.HasIndex("Reason", "SurfaceForm");

                    b.ToTable("PostingMentions", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.PostingTagEntity", b =>
                {
                    b.Property<long>("PostingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Tag")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Value")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PostingId", "Tag");

                    b.HasIndex("Tag");

                    b.ToTable("PostingTags", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ProfileCertificationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Issuer")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "Ordinal");

                    b.ToTable("ProfileCertifications", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ProfileConceptEntity", b =>
                {
                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<int>("ConceptId")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<double?>("Confidence")
                        .HasColumnType("float");

                    b.Property<string>("EvidenceText")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Polarity")
                        .HasColumnType("int");

                    b.Property<int>("ResolverVersion")
                        .HasColumnType("int");

                    b.Property<int?>("YearsMax")
                        .HasColumnType("int");

                    b.Property<int?>("YearsMin")
                        .HasColumnType("int");

                    b.HasKey("ProfileId", "ConceptId", "Source");

                    b.HasIndex("ConceptId", "ProfileId");

                    b.ToTable("ProfileConcepts", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ProfileEducationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("FieldOfStudy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Grade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "Ordinal");

                    b.ToTable("ProfileEducation", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ProfileEmbeddingEntity", b =>
                {
                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<int>("Dimensions")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("EmbeddedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EmbeddingVersion")
                        .HasColumnType("int");

                    b.Property<string>("InputHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Vector")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ProfileId");

                    b.ToTable("ProfileEmbeddings", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ProfileExperienceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("LocationCity")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LocationCountry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "Ordinal");

                    b.ToTable("ProfileExperiences", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ProfileJobTypeEntity", b =>
                {
                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<string>("JobType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ProfileId", "JobType");

                    b.ToTable("ProfileJobTypes", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ProfileLanguageEntity", b =>
                {
                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Level")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProfileId", "Name");

                    b.ToTable("ProfileLanguages", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ProfileLinkEntity", b =>
                {
                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<string>("Label")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("ProfileId", "Label");

                    b.ToTable("ProfileLinks", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ProfileMentionEntity", b =>
                {
                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<string>("SurfaceForm")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Occurrences")
                        .HasColumnType("int");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<int>("ResolverVersion")
                        .HasColumnType("int");

                    b.HasKey("ProfileId", "SurfaceForm");

                    b.HasIndex("Reason", "SurfaceForm");

                    b.ToTable("ProfileMentions", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ProfileProjectEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("CompletedOn")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "Ordinal");

                    b.ToTable("ProfileProjects", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ScrapeRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobETag")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long>("BlobSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("DurationMs")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("IngestedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("InvalidCount")
                        .HasColumnType("int");

                    b.Property<int>("NewCount")
                        .HasColumnType("int");

                    b.Property<int>("ParsedCount")
                        .HasColumnType("int");

                    b.Property<int>("RowCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ScrapeDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("ScrapedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SearchTerm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UnchangedCount")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlobPath")
                        .IsUnique();

                    b.HasIndex("SearchTerm", "ScrapeDate");

                    b.ToTable("ScrapeRuns", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ScraperSearchEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CountryIndeed")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<int?>("HoursOld")
                        .HasColumnType("int");

                    b.Property<bool?>("IsRemote")
                        .HasColumnType("bit");

                    b.Property<string>("JobType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("OwnerSubjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("ResultsWanted")
                        .HasColumnType("int");

                    b.Property<string>("SearchTerm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("OwnerSubjectId", "Name")
                        .IsUnique();

                    b.ToTable("ScraperSearches", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ScraperSearchFilterEntity", b =>
                {
                    b.Property<long>("SearchId")
                        .HasColumnType("bigint");

                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SearchId", "Key");

                    b.ToTable("ScraperSearchFilters", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ScraperSearchSiteEntity", b =>
                {
                    b.Property<long>("SearchId")
                        .HasColumnType("bigint");

                    b.Property<string>("Site")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("SearchId", "Site");

                    b.ToTable("ScraperSearchSites", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.SubmissionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ApplyUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("PostingId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PostingId");

                    b.HasIndex("ProfileId", "CreatedAtUtc");

                    b.HasIndex("ProfileId", "PostingId")
                        .IsUnique();

                    b.ToTable("Submissions", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.SubmissionEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("Stage")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<long>("SubmissionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId", "AtUtc");

                    b.HasIndex("SubmissionId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("SubmissionEvents", (string)null);
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ApplicationDocumentEntity", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.JobPostingEntity", "Posting")
                        .WithMany()
                        .HasForeignKey("PostingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobPlatform.Data.Sql.Entities.CandidateProfileEntity", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posting");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ConceptClosureEntity", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.ConceptEntity", "Ancestor")
                        .WithMany()
                        .HasForeignKey("AncestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobPlatform.Data.Sql.Entities.ConceptEntity", "Descendant")
                        .WithMany()
                        .HasForeignKey("DescendantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ancestor");

                    b.Navigation("Descendant");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ConceptLabelEntity", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.ConceptEntity", "Concept")
                        .WithMany("Labels")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concept");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ConceptRelationEntity", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.ConceptEntity", "FromConcept")
                        .WithMany()
                        .HasForeignKey("FromConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobPlatform.Data.Sql.Entities.ConceptEntity", "ToConcept")
                        .WithMany()
                        .HasForeignKey("ToConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromConcept");

                    b.Navigation("ToConcept");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ExtractionBatchItemEntity", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.ExtractionBatchEntity", "Batch")
                        .WithMany("Items")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobPlatform.Data.Sql.Entities.JobPostingEntity", "Posting")
                        .WithMany()
                        .HasForeignKey("PostingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Posting");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.JobMatchEntity", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.JobPostingEntity", "Posting")
                        .WithMany()
                        .HasForeignKey("PostingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobPlatform.Data.Sql.Entities.CandidateProfileEntity", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posting");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.JobPostingEntity", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.CompanyEntity", "CompanyRef")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CompanyRef");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.JobPostingJobTypeEntity", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.JobPostingEntity", "Posting")
                        .WithMany("JobTypes")
                        .HasForeignKey("PostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posting");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.JobPostingSearchTerm", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.ScrapeRun", "FirstSeenRun")
                        .WithMany()
                        .HasForeignKey("FirstSeenRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobPlatform.Data.Sql.Entities.ScrapeRun", "LastSeenRun")
                        .WithMany()
                        .HasForeignKey("LastSeenRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobPlatform.Data.Sql.Entities.JobPostingEntity", "Posting")
                        .WithMany("SearchTerms")
                        .HasForeignKey("PostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirstSeenRun");

                    b.Navigation("LastSeenRun");

                    b.Navigation("Posting");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.PostingConceptEntity", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.ConceptEntity", "Concept")
                        .WithMany()
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobPlatform.Data.Sql.Entities.JobPostingEntity", "Posting")
                        .WithMany("Concepts")
                        .HasForeignKey("PostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concept");

                    b.Navigation("Posting");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.PostingEmbeddingEntity", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.JobPostingEntity", "Posting")
                        .WithMany()
                        .HasForeignKey("PostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posting");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.PostingExtractionEntity", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.JobPostingEntity", "Posting")
                        .WithMany("Extractions")
                        .HasForeignKey("PostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posting");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.PostingMentionEntity", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.JobPostingEntity", "Posting")
                        .WithMany("Mentions")
                        .HasForeignKey("PostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posting");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.PostingTagEntity", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.JobPostingEntity", "Posting")
                        .WithMany("Tags")
                        .HasForeignKey("PostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posting");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ProfileCertificationEntity", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.CandidateProfileEntity", "Profile")
                        .WithMany("Certifications")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ProfileConceptEntity", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.ConceptEntity", "Concept")
                        .WithMany()
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobPlatform.Data.Sql.Entities.CandidateProfileEntity", "Profile")
                        .WithMany("Concepts")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concept");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ProfileEducationEntity", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.CandidateProfileEntity", "Profile")
                        .WithMany("Education")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ProfileEmbeddingEntity", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.CandidateProfileEntity", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ProfileExperienceEntity", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.CandidateProfileEntity", "Profile")
                        .WithMany("Experiences")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ProfileJobTypeEntity", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.CandidateProfileEntity", "Profile")
                        .WithMany("JobTypes")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ProfileLanguageEntity", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.CandidateProfileEntity", "Profile")
                        .WithMany("Languages")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ProfileLinkEntity", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.CandidateProfileEntity", "Profile")
                        .WithMany("Links")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ProfileMentionEntity", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.CandidateProfileEntity", "Profile")
                        .WithMany("Mentions")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ProfileProjectEntity", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.CandidateProfileEntity", "Profile")
                        .WithMany("Projects")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ScraperSearchFilterEntity", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.ScraperSearchEntity", "Search")
                        .WithMany("Filters")
                        .HasForeignKey("SearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Search");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ScraperSearchSiteEntity", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.ScraperSearchEntity", "Search")
                        .WithMany("Sites")
                        .HasForeignKey("SearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Search");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.SubmissionEntity", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.JobPostingEntity", "Posting")
                        .WithMany()
                        .HasForeignKey("PostingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobPlatform.Data.Sql.Entities.CandidateProfileEntity", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posting");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.SubmissionEventEntity", b =>
                {
                    b.HasOne("JobPlatform.Data.Sql.Entities.SubmissionEntity", "Submission")
                        .WithMany("Events")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.CandidateProfileEntity", b =>
                {
                    b.Navigation("Certifications");

                    b.Navigation("Concepts");

                    b.Navigation("Education");

                    b.Navigation("Experiences");

                    b.Navigation("JobTypes");

                    b.Navigation("Languages");

                    b.Navigation("Links");

                    b.Navigation("Mentions");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ConceptEntity", b =>
                {
                    b.Navigation("Labels");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ExtractionBatchEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.JobPostingEntity", b =>
                {
                    b.Navigation("Concepts");

                    b.Navigation("Extractions");

                    b.Navigation("JobTypes");

                    b.Navigation("Mentions");

                    b.Navigation("SearchTerms");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.ScraperSearchEntity", b =>
                {
                    b.Navigation("Filters");

                    b.Navigation("Sites");
                });

            modelBuilder.Entity("JobPlatform.Data.Sql.Entities.SubmissionEntity", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
